package contest;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'wang' at '15/04/01 10:37' with Gradle 2.3
 *
 * @author wang, @date 15/04/01 10:37
 */
public class LibraryTest {
    protected static Logger log = LoggerFactory.getLogger(LibraryTest.class);

    @Test public void testSomeLibraryMethod() {
        log.info("start test {}", this.getClass().getName());
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
