package contest;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wang' at '15/04/01 10:37' with Gradle 2.3
 *
 * @author wang, @date 15/04/01 10:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
